services:
  - name: frontend
    env: docker
    buildCommand: docker build -t $RENDER_IMAGE_NAME -f frontend/Dockerfile .
    startCommand: docker run -p 80:80 $RENDER_IMAGE_NAME
    healthCheckPath: /

  - name: backend
    env: docker
    buildCommand: docker build -t $RENDER_IMAGE_NAME -f backend/Dockerfile .
    startCommand: docker run -p 5000:5000 $RENDER_IMAGE_NAME
    healthCheckPath: /

buildCommand:
  - echo "Build complete."

healthCheckPath: /
