services:
  # A Docker web service
  - type: web
    name: frontend
    runtime: docker
    rootDir: frontend
    healthCheckPath: /
  - type: web
    name: backend
    runtime: docker
    rootDir: backend
    healthCheckPath: /
